---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidyverse")
library(readxl)
library(pdSpecEst)
library(correlation)
library(psych)

diag1 <- function(X) {
  diag(X) <- 1
  return(X)
}

UT <- function(x) {
  return(x[upper.tri(x)])
}

jaccard_d <- function(x,y) {
  # calculates weighted Jaccard similarity between
  # x and y (positive vectors of equal length)
  if(length(x)!=length(y)) {
    warning("vectors must be of the same length")
  } else if(any(!(c(x,y) %in%  c(0,1)))) {
    warning("all elements must be 0 or 1")
  } else {
    M_11 <- sum(x==1 & y==1)
    M_01 <- sum(x==0 & y==1)
    M_10 <- sum(x==1 & y==0)
    Jaccard <- (M_01+M_10)/(M_01+M_10+M_11)
    vec <- c(Jaccard)
    names(vec) <- c("Jaccard Dist")    
    return(t(vec))
  }
}

subIDs <- as.vector(as.matrix(read.csv("flists/sub_ids.csv",header = F)))
scantypes <- paste(rep(c("WM","RS"),each=4),
                   rep(rep(c("ses1","ses2"),each=2),times=2),
                   rep(c("LR","RL"),times=4),
                   sep="_")
scans <- paste(rep(subIDs,each=length(scantypes)),
              rep(scantypes,time=length(subIDs)),
              sep="_")
scans_df <- tidyr::separate(as.data.frame(scans),col=scans,sep="_",into=c("ID","TASK","SES","PHASE"))
rownames(scans_df) <- scans

CM_weight <- CM_top005 <- matrix(nrow = length(subIDs)*8,ncol = choose(268,2),
  dimnames = list(scans,1:choose(268,2)))

for(subID in subIDs) {
  for(task in c("WM","RS")) {
    for(session in c("ses1","ses2")) {
      for(phase in c("LR","RL")) {
        tmp_id <- paste(subID,task,session,phase,sep="_")
        assign(tmp_id,
           cor_smooth(diag1(as.matrix(read.csv(paste0("/isilon/datalake/lcbn_research/final/HCP/",
                                           ifelse(session=="ses1","HCP_1200","HCP_45"),
                                           "/Networks/",
                                           subID,
                                           "/",
                                           ifelse(task=="WM","tfMRI_WM","rfMRI_REST1"),
                                           "/network/Atlas_Yale/CorrData/../",
                                           phase,
                                           "/Aij.csv"), header = F))),verbose=F,tol=10^-12))
        CM_weight[tmp_id,] <- UT(get(tmp_id))
        CM_top005[tmp_id,] <- CM_weight[tmp_id,] > quantile(CM_weight[tmp_id,],1-.005)
      }
    }
  }
}

cov_r <- as.data.frame(filter(read_excel("/isilon/datalake/lcbn_research/final/HCP/Demographics/Demographics_Restricted.xlsx"), Subject %in% subIDs))
rownames(cov_r) <- cov_r$Subject
cov_r$Fam0 <- cov_r$Family_ID 
cov_r$Fam0[cov_r$Family_ID %in% names(table(cov_r$Fam0)[table(cov_r$Fam0)==1])] <- 0

cov_u <- filter(read.csv("/isilon/datalake/lcbn_research/final/HCP/Demographics/Demographics_Unrestricted.csv"), Subject %in% subIDs)
rownames(cov_u) <- cov_u$Subject

df_dist <- as.data.frame(matrix(NA,nrow=choose(length(scans),2),ncol=1,dimnames = list(NULL,c("SCANIDa"))))

counter = 1

for(i in 1:(length(scans)-1)) {
    for(j in (i+1):length(scans)) {
      
      scan_i <- scans[i]
      scan_j <- scans[j]
      
      df_dist[counter,"SCANIDa"] <- scan_i
      df_dist[counter,"SCANIDb"] <- scan_j
      
      df_dist[counter,c("IDa","TASKa","SESa","PHASEa")] <- scans_df[scan_i,c("ID","TASK","SES","PHASE")]
      df_dist[counter,c("IDb","TASKb","SESb","PHASEb")] <- scans_df[scan_j,c("ID","TASK","SES","PHASE")]
      
      id_i <- df_dist$IDa[counter]
      id_j <- df_dist$IDb[counter]
      
      df_dist[counter,c("FamIDa","Fam0IDa")] <- cov_r[id_i,c("Family_ID","Fam0")]
      df_dist[counter,c("FamIDb","Fam0IDb")] <- cov_r[id_j,c("Family_ID","Fam0")]
      
      df_dist[counter,"FluidIntl"] = abs(cov_u[id_i,"PMAT24_A_CR"] - cov_u[id_j,"PMAT24_A_CR"])
      df_dist[counter,"Gender"] = 1*(cov_u[id_i,"Gender"] != cov_u[id_j,"Gender"])
      df_dist[counter,"Age"] = abs(cov_r[id_i,"Age_in_Yrs"] - cov_r[id_j,"Age_in_Yrs"])
      df_dist[counter,"Education"] = abs(cov_r[id_i,"SSAGA_Educ"] - cov_r[id_j,"SSAGA_Educ"])
      df_dist[counter,"BMI"] = abs(cov_r[id_i,"BMI"] - cov_r[id_j,"BMI"])
      df_dist[counter,"Race"] = 1*(cov_r[id_i,"Race"] != cov_r[id_j,"Race"])
      df_dist[counter,"Ethnicity"] = 1*(cov_r[id_i,"Ethnicity"] != cov_r[id_j,"Ethnicity"])
      df_dist[counter,"Handedness"] = abs(cov_r[id_i,"Handedness"] - cov_r[id_j,"Handedness"])
      df_dist[counter,"Income"] = abs(cov_r[id_i,"SSAGA_Income"] - cov_r[id_j,"SSAGA_Income"])
      df_dist[counter,"DSM4_Alc_Abuse"] = 1*(cov_r[id_i,"SSAGA_Alc_D4_Ab_Dx"] != cov_r[id_j,"SSAGA_Alc_D4_Ab_Dx"])
      df_dist[counter,"DSM4_Alc_Dep"] = 1*(cov_r[id_i,"SSAGA_Alc_D4_Dp_Dx"] != cov_r[id_j,"SSAGA_Alc_D4_Dp_Dx"])
      df_dist[counter,"SmokeStatus"] = 1*(cov_r[id_i,"SSAGA_TB_Still_Smoking"] != cov_r[id_j,"SSAGA_TB_Still_Smoking"])
      
      df_dist[counter,"JAC"] = jaccard_d(CM_top005[scan_i,],CM_top005[scan_j,])
      df_dist[counter,"KS"] = suppressWarnings(ks.test(CM_weight[scan_i,],CM_weight[scan_j,]))$statistic
      df_dist[counter,"EUC"] = dist(rbind(CM_weight[scan_i,],CM_weight[scan_j,]),method = "euclidean")
      df_dist[counter,"LERM"] = pdDist(get(scan_i),get(scan_j),metric = "logEuclidean")

      counter = counter + 1
    }
}

saveRDS(df_dist,"HCP_mixed_distdf_CM.Rds")
```

```{r}
df <- readRDS("HCP_mixed_distdf_CM.Rds") %>% filter(FamIDa != FamIDb,TASKa == TASKb)

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$KS),ylim=c(0,30))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$KS))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$KS),ylim=c(0,30))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$KS))

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$JAC),ylim=c(0,15))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$JAC))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$JAC),ylim=c(0,15))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$JAC))

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$EUC),ylim=c(0,0.13))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$EUC))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$EUC),ylim=c(0,0.13))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$EUC))

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$LERM),ylim=c(0,0.30))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$LERM))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$LERM),ylim=c(0,0.20))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$LERM))
```

```{r}
df <- readRDS("HCP_mixed_distdf_CM.Rds")
cov_r <- as.data.frame(filter(read_excel("Demographics_Restricted.xlsx"), Subject %in% unique(c(df$IDa,df$IDb))))
rownames(cov_r) <- cov_r$Subject
cov_u <- filter(read.csv("Demographics_Unrestricted.csv"), Subject %in% unique(c(df$IDa,df$IDb)))
rownames(cov_u) <- cov_u$Subject


IDs <- as.character(cov_r %>% group_by(Family_ID) %>% slice(1) %>% pull(Subject))
print("fluidintl")
round(mean(cov_u[IDs,"PMAT24_A_CR"]),1)
round(sd(cov_u[IDs,"PMAT24_A_CR"]),1)
print("Age")
round(mean(cov_r[IDs,"Age_in_Yrs"]),1)
round(sd(cov_r[IDs,"Age_in_Yrs"]),1)
print("BMI")
round(mean(cov_r[IDs,"BMI"]),1)
round(sd(cov_r[IDs,"BMI"]),1)
print("Education")
round(mean(cov_r[IDs,"SSAGA_Educ"]),1)
round(sd(cov_r[IDs,"SSAGA_Educ"]),1)
print("Handedness")
round(mean(cov_r[IDs,"Handedness"]),1)
round(sd(cov_r[IDs,"Handedness"]),1)
print("Income")
round(mean(cov_r[IDs,"SSAGA_Income"]),1)
round(sd(cov_r[IDs,"SSAGA_Income"]),1)

print("Income (Table)")
table(cov_r[IDs,"SSAGA_Income"])
print("Handedness (Table)")
table(cov_r[IDs,"Handedness"])
print("Education (Table)")
table(cov_r[IDs,"SSAGA_Educ"])
print("Gender (Table)")
table(cov_u[IDs,"Gender"])
print("Race (Table)")
table(cov_r[IDs,"Race"])
print("Ethnicity (Table)")
table(cov_r[IDs,"Ethnicity"]) # REMOVED
print("Income (Table)")
table(cov_r[IDs,"SSAGA_Income"])
print("Alcohol Abuse (Table)")
table(cov_r[IDs,"SSAGA_Alc_D4_Ab_Dx"]) # REMOVED
print("Alcohol Dependence (Table)")
table(cov_r[IDs,"SSAGA_Alc_D4_Dp_Dx"]) # REMOVED
print("Smoking (Table)")
table(cov_r[IDs,"SSAGA_TB_Still_Smoking"])


df <- readRDS("HCP_mixed_distdf_CM.Rds") %>% filter(IDa %in% IDs & IDb %in% IDs, IDa != IDb, TASKa == TASKb, TASKa=="RS" | PHASEa == PHASEb)
  lvls <- unique(c(df$SCANIDa,df$SCANIDb))
  df$SCANIDa <- factor(df$SCANIDa, levels = lvls)
  df$SCANIDb <- factor(df$SCANIDb, levels = lvls)
  SCANIDmat <- model.matrix(~SCANIDa-1,data=df)+model.matrix(~SCANIDb-1,data=df)
  colnames(SCANIDmat) <- gsub("^.{0,7}", "", colnames(SCANIDmat))
  df$Task_Phase <- ifelse(df$TASKa=="RS","RS",paste(df$TASKa,df$PHASEb, sep = "_"))
  df$ID_ID <- factor(paste0(df$IDa,"_",df$IDb))
  
  results_EUC <- summary(lmer(EUC ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_JAC <- summary(lmer(JAC ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_KS <- summary(lmer(KS ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_LERM <- summary(lmer(LERM ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  
  write.csv(cbind(results_KS,results_JAC,results_EUC,results_LERM),file="hcp_results_mixed_CM_26.csv")
```



```{r}
library(tidyverse)
library(readxl)

jaccard_d <- function(x,y) {
  # calculates weighted Jaccard similarity between
  # x and y (positive vectors of equal length)
  if(length(x)!=length(y)) {
    warning("vectors must be of the same length")
  } else if(any(!(c(x,y) %in%  c(0,1)))) {
    warning("all elements must be 0 or 1")
  } else {
    M_11 <- sum(x==1 & y==1)
    M_01 <- sum(x==0 & y==1)
    M_10 <- sum(x==1 & y==0)
    Jaccard <- (M_01+M_10)/(M_01+M_10+M_11)
    vec <- c(Jaccard)
    names(vec) <- c("Jaccard Dist")    
    return(t(vec))
  }
}

subIDs <- as.vector(as.matrix(read.csv("flists/sub_ids.csv",header = F)))
scantypes <- paste(rep(c("WM","RS"),each=4),
                   rep(rep(c("ses1","ses2"),each=2),times=2),
                   rep(c("LR","RL"),times=4),
                   sep="_")
scans <- paste(rep(subIDs,each=length(scantypes)),
              rep(scantypes,time=length(subIDs)),
              sep="_")
scans_df <- tidyr::separate(as.data.frame(scans),col=scans,sep="_",into=c("ID","TASK","SES","PHASE"))
rownames(scans_df) <- scans

ND_weight <- ND_top05 <- ND_top20 <- matrix(nrow = length(subIDs)*8,ncol = 268,
  dimnames = list(scans,1:268))

for(subID in subIDs) {
  for(task in c("WM","RS")) {
    for(session in c("ses1","ses2")) {
      for(phase in c("LR","RL")) {
        tmp_id <- paste(subID,task,session,phase,sep="_")
        ND_weight[tmp_id,] <- rowSums(
                                pmax(as.matrix(read.csv(paste0("/isilon/datalake/lcbn_research/final/HCP/",
                                           ifelse(session=="ses1","HCP_1200","HCP_45"),
                                           "/Networks/",
                                           subID,
                                           "/",
                                           ifelse(task=="WM","tfMRI_WM","rfMRI_REST1"),
                                           "/network/Atlas_Yale/CorrData/../",
                                           phase,
                                           "/Aij.csv"), header = F)),
                                     0))
        ND_top05[tmp_id,] <- ND_weight[tmp_id,] > quantile(ND_weight[tmp_id,],1-.05)
        ND_top20[tmp_id,] <- ND_weight[tmp_id,] > quantile(ND_weight[tmp_id,],1-.20)
      }
    }
  }
}

cov_r <- as.data.frame(filter(read_excel("/isilon/datalake/lcbn_research/final/HCP/Demographics/Demographics_Restricted.xlsx"), Subject %in% subIDs))
rownames(cov_r) <- cov_r$Subject
cov_r$Fam0 <- cov_r$Family_ID 
cov_r$Fam0[cov_r$Family_ID %in% names(table(cov_r$Fam0)[table(cov_r$Fam0)==1])] <- 0

cov_u <- filter(read.csv("/isilon/datalake/lcbn_research/final/HCP/Demographics/Demographics_Unrestricted.csv"), Subject %in% subIDs)
rownames(cov_u) <- cov_u$Subject

df_dist <- as.data.frame(matrix(NA,nrow=choose(length(scans),2),ncol=1,dimnames = list(NULL,c("SCANIDa"))))

counter = 1

for(i in 1:(length(scans)-1)) {
    for(j in (i+1):length(scans)) {
      
      scan_i <- scans[i]
      scan_j <- scans[j]
      
      df_dist[counter,"SCANIDa"] <- scan_i
      df_dist[counter,"SCANIDb"] <- scan_j
      
      df_dist[counter,c("IDa","TASKa","SESa","PHASEa")] <- scans_df[scan_i,c("ID","TASK","SES","PHASE")]
      df_dist[counter,c("IDb","TASKb","SESb","PHASEb")] <- scans_df[scan_j,c("ID","TASK","SES","PHASE")]
      
      id_i <- df_dist$IDa[counter]
      id_j <- df_dist$IDb[counter]
      
      df_dist[counter,"FamIDa"] <- cov_r[id_i,"Family_ID"]
      df_dist[counter,"FamIDb"] <- cov_r[id_j,"Family_ID"]
      
      df_dist[counter,c("FamIDa","Fam0IDa")] <- cov_r[id_i,c("Family_ID","Fam0")]
      df_dist[counter,c("FamIDb","Fam0IDb")] <- cov_r[id_j,c("Family_ID","Fam0")]
      
      df_dist[counter,"FluidIntl"] = abs(cov_u[id_i,"PMAT24_A_CR"] - cov_u[id_j,"PMAT24_A_CR"])
      df_dist[counter,"Gender"] = 1*(cov_u[id_i,"Gender"] != cov_u[id_j,"Gender"])
      df_dist[counter,"Age"] = abs(cov_r[id_i,"Age_in_Yrs"] - cov_r[id_j,"Age_in_Yrs"])
      df_dist[counter,"Education"] = abs(cov_r[id_i,"SSAGA_Educ"] - cov_r[id_j,"SSAGA_Educ"])
      df_dist[counter,"BMI"] = abs(cov_r[id_i,"BMI"] - cov_r[id_j,"BMI"])
      df_dist[counter,"Race"] = 1*(cov_r[id_i,"Race"] != cov_r[id_j,"Race"])
      df_dist[counter,"Ethnicity"] = 1*(cov_r[id_i,"Ethnicity"] != cov_r[id_j,"Ethnicity"])
      df_dist[counter,"Handedness"] = abs(cov_r[id_i,"Handedness"] - cov_r[id_j,"Handedness"])
      df_dist[counter,"Income"] = abs(cov_r[id_i,"SSAGA_Income"] - cov_r[id_j,"SSAGA_Income"])
      df_dist[counter,"DSM4_Alc_Abuse"] = 1*(cov_r[id_i,"SSAGA_Alc_D4_Ab_Dx"] != cov_r[id_j,"SSAGA_Alc_D4_Ab_Dx"])
      df_dist[counter,"DSM4_Alc_Dep"] = 1*(cov_r[id_i,"SSAGA_Alc_D4_Dp_Dx"] != cov_r[id_j,"SSAGA_Alc_D4_Dp_Dx"])
      df_dist[counter,"SmokeStatus"] = 1*(cov_r[id_i,"SSAGA_TB_Still_Smoking"] != cov_r[id_j,"SSAGA_TB_Still_Smoking"])
      
      df_dist[counter,"JAC05"] = jaccard_d(ND_top05[scan_i,],ND_top05[scan_j,])
      df_dist[counter,"JAC20"] = jaccard_d(ND_top20[scan_i,],ND_top20[scan_j,])
      df_dist[counter,"KS"] = suppressWarnings(ks.test(ND_weight[scan_i,],ND_weight[scan_j,]))$statistic
      df_dist[counter,"EUC"] = dist(rbind(ND_weight[scan_i,],ND_weight[scan_j,]),method = "euclidean")
      #df_dist[counter,"LERM"] = pdDist(get(scan_i),get(scan_j),metric = "logEuclidean")

      counter = counter + 1
    }
}

saveRDS(df_dist,"HCP_mixed_distdf_ND.Rds")
```

```{r}
df <- readRDS("HCP_mixed_distdf_ND.Rds") %>% filter(FamIDa != FamIDb,TASKa == TASKb)

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$KS),ylim=c(0,5))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$KS))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$KS),ylim=c(0,5))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$KS))

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$JAC05),ylim=c(0,10))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$JAC05))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$JAC05),ylim=c(0,10))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$JAC05))

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$JAC20),ylim=c(0,8))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$JAC20))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$JAC20),ylim=c(0,5))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$JAC20))

plot(density((df %>% filter(TASKa == "WM",PHASEa=="LR",PHASEb=="LR"))$EUC),ylim=c(0,0.015))
lines(density((df %>% filter(TASKa == "WM",PHASEa=="RL",PHASEb=="RL"))$EUC))

plot(density((df %>% filter(TASKa == "RS",PHASEa=="LR",PHASEb=="LR"))$EUC),ylim=c(0,0.02))
lines(density((df %>% filter(TASKa == "RS",PHASEa=="RL",PHASEb=="RL"))$EUC))

```

```{r}
df <- readRDS("HCP_mixed_distdf_ND.Rds") %>% filter(FamIDa != FamIDb, IDa %in% IDs & IDb %in% IDs, IDa != IDb, TASKa == TASKb, TASKa=="RS" | PHASEa == PHASEb)
  lvls <- unique(c(df$SCANIDa,df$SCANIDb))
  df$SCANIDa <- factor(df$SCANIDa, levels = lvls)
  df$SCANIDb <- factor(df$SCANIDb, levels = lvls)
  SCANIDmat <- model.matrix(~SCANIDa-1,data=df)+model.matrix(~SCANIDb-1,data=df)
  colnames(SCANIDmat) <- gsub("^.{0,7}", "", colnames(SCANIDmat))
  df$Task_Phase <- ifelse(df$TASKa=="RS","RS",paste(df$TASKa,df$PHASEb, sep = "_"))
  df$ID_ID <- factor(paste0(df$IDa,"_",df$IDb))
  
  results_EUC <- summary(lmer(EUC ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_JAC05 <- summary(lmer(JAC05 ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_JAC20 <- summary(lmer(JAC20 ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_KS <- summary(lmer(KS ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):Task_Phase - 1 + (Task_Phase|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  
  write.csv(cbind(results_KS,results_JAC05,results_JAC20,results_EUC),file="hcp_results_mixed_ND_26.csv")
```

```{r}
df <-  readRDS("HCP_mixed_distdf_ND.Rds") %>% filter(FamIDa != FamIDb,IDa %in% IDs & IDb %in% IDs, IDa != IDb, TASKa == TASKb)
  lvls <- unique(c(df$SCANIDa,df$SCANIDb))
  df$SCANIDa <- factor(df$SCANIDa, levels = lvls)
  df$SCANIDb <- factor(df$SCANIDb, levels = lvls)
  SCANIDmat <- model.matrix(~SCANIDa-1,data=df)+model.matrix(~SCANIDb-1,data=df)
  colnames(SCANIDmat) <- gsub("^.{0,7}", "", colnames(SCANIDmat))
  df$ID_ID <- factor(paste0(df$IDa,"_",df$IDb))
  
  results_EUC <- summary(lmer(EUC ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):TASKa - 1 + (TASKa|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_JAC05 <- summary(lmer(JAC05 ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):TASKa - 1 + (TASKa|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_JAC20 <- summary(lmer(JAC20 ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):TASKa - 1 + (TASKa|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  results_KS <- summary(lmer(KS ~ SCANIDmat + (FluidIntl + Gender + Age + Education + BMI + Race + Handedness + Income +  SmokeStatus):TASKa - 1 + (TASKa|ID_ID), data=df))$coefficients[-c(1:(26*8)),]
  
  write.csv(cbind(results_KS,results_JAC05,results_JAC20,results_EUC),file="hcp_results_mixed_ND_26b.csv")
```
